### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by kmy8228** [kmy8228/gh-flow-practice#2]
## Tasks

- [ ] Print fizz, if i is multiple of 3.
- [ ] Print buzz, if i in multiple of 5.
- [ ] Print fizzbuzz, if i is multiple of 15.
- [ ] Otherwise, print i itself.

## References

- [Fizzbuzz wikipedia](https://en.wikipedia.org/wiki/Fizz_buzz)
